-- CONSULTA NORMAL PUXANDO TUDO DA TABELA COMO ELA FOI FEITA
SELECT * FROM TABELA_DE_CLIENTES;

-- CONSULTA COM ALIAS
SELECT NOME AS "NOME DO CLIENTE", 
CPF AS "CPF DO CLIENTE", 
CIDADE AS "CIDADE DO CLIENTE",
BAIRRO AS "BAIRRO DO CLIENTE"
FROM TABELA_DE_CLIENTES;

-- CONSULTA TROCANDO O NOME DA TABELA
SELECT NOME AS "NOME DO CLIENTE", 
CPF AS "CPF DO CLIENTE", 
CIDADE AS "CIDADE DO CLIENTE",
CLIENTES.BAIRRO AS "BAIRRO DO CLIENTE"
FROM TABELA_DE_CLIENTES CLIENTES;

-- CONSULTA NORMAL, APENAS UTILIZANDO O ALIAS DA TABELA PARA CHAMAR TUDO
SELECT CLIENTES.*
FROM TABELA_DE_CLIENTES CLIENTES;