select * from tabela_de_clientes;
-- MAIOR QUE 18
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 18;
-- MENOR QUE 18
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 18;
-- DIFERENTE DE 18
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;
-- = 18
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE = 18;
-- BR
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '10/05/95';
-- US
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO_DATE('10/05/1995', 'MM/DD/YYYY');
-- ENTRE IDADES
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 19 AND 24;

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa';
