-- Consulta normal
SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;
-- Consulta sem repeticoes
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;
-- Consulta sem repeticoes com filtro
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';
-- Consulta com mais de um campo
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT SABOR FROM tabela_de_produtos;