SELECT * FROM TABELA_DE_PRODUTOS
WHERE ROWNUM <= 10;

SELECT ROWNUM, TP.* 
FROM TABELA_DE_PRODUTOS TP;

SELECT ROWNUM, TP.* 
FROM TABELA_DE_PRODUTOS TP
WHERE ROWNUM <= 5;

SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '01/10/2017' AND ROWNUM <= 10;

