SELECT PRECO_DE_LISTA, (CASE WHEN PRECO_DE_LISTA >= 15 THEN 'CARO' ELSE 'BARATO' END) 
AS "BARATO OU CARO"
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_dE_LISTA DESC;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, (
CASE WHEN PRECO_DE_LISTA >= 15 THEN 'PRODUTO CARO'
WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 15 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO'
END) AS "CLASSIFICACAO DE PRODUTOS"
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, (
CASE WHEN PRECO_DE_LISTA >= 15 THEN 'PRODUTO CARO'
WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 15 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO'
END) AS "CLASSIFICACAO DE PRODUTOS"
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga';

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, (
CASE WHEN PRECO_DE_LISTA >= 15 THEN 'PRODUTO CARO'
WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 15 THEN 'PRODUTO EM CONTA'
ELSE 'PRODUTO BARATO'
END) AS "CLASSIFICACAO DE PRODUTOS"
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA;