-- ATIVIDADE

SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, LIMITE_DE_CREDITO, (CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
WHEN LIMITE_DE_CREDITO <= 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'CLIENTE MEDIO'
ELSE 'CLIENTE PEQUENO'
END)
FROM TABELA_DE_CLIENTES
ORDER BY LIMITE_DE_CREDITO DESC;
