SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(QUANTIDADE) AS "QUANTIDADE VENDIDA" 
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO 
GROUP BY TP.NOME_DO_PRODUTO, INF.CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE) DESC;
