-- hard code

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN (
'Tijuca',
'Jardins',
'Copacabana',
'Santo Amaro');

-- SIMPLE

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN (
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);


