SELECT NOME FROM TABELA_DE_CLIENTES;
-- LOWERCASE
SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;
-- UPPERCASE
SELECT NOME, UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO FROM TABELA_dE_PRODUTOS;
-- INICIO DE CADA PALAVRA COM LETRA MAICUSCULA
SELECT INITCAP(NOME_DO_PRODUTO) FROM TABELA_dE_PRODUTOS;

SELECT ENDERECO_1, BAIRRO FROM TABELA_DE_CLIENTES;
-- CONCATENACAO COM A FUNCAO CONCAT
SELECT CONCAT(CONCAT(ENDERECO_1, ' | '), BAIRRO) FROM TABELA_DE_CLIENTES;
-- CONCATENACAO COM ||
SELECT ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ' ' || CEP || ' '  
FROM TABELA_DE_CLIENTES;
-- PREENCHE O QUE FALTAVA ATE OS 70 DA ESQUERDA PRA DIREITA
SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;
-- PREENCHE O QUE FALTAVA ATE OS 70 DA DIREITA PRA ESQUERDA
SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;
-- PEGA NO CASO DO TERCEIRO CARACTERE ATE O 5 DEPOIS DO 3 CARACTERE
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 3, 5) FROM TABELA_dE_PRODUTOS;
-- PROCURA DENTRO DA STRING PRODUTOS QUE TENHAM A PALAVRA CAMPO DENTRO DELA
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, 'Campo') FROM TABELA_DE_PRODUTOS;
-- PROCURA DENTRO DA STRING NOMES QUE TENHAM MATTOS
SELECT NOME, INSTR(NOME, 'Mattos')FROM TABELA_DE_CLIENTES;
-- PROCURA DENTRO DA STRING NOMES QUE TENHAM MATTOS POREM COM FILTRO PARA APARECER SOMENTE OS TRUE
SELECT NOME FROM TABELA_DE_CLIENTES
WHERE INSTR(NOME, 'Mattos') <> 0;
-- RETIRA OS ESPACOS EM BRANCO DA ESQUERDA DA STRING
SELECT LTRIM('            VICTORIANO         ') AS A FROM DUAL;
-- RETIRA OS ESPACOS EM BRANCO DA DIREITA DA STRING
SELECT RTRIM('            VICTORIANO         ')AS Z FROM DUAL;
-- RETIRA OS ESPACOS EM BRANCO DA DIREITA DA STRING
SELECT TRIM('            VICTORIANO         ') AS W FROM DUAL;
-- SUBSTITUI A PALAVRA LITRO DO NOME DO PRODUTO POR L
SELECT REPLACE(NOME_DO_PRODUTO,'Litro', 'L') FROM TABELA_DE_PRODUTOS;
-- SUBSTITUI A PALAVRA LITRO DO NOME DO PRODUTO POR L E SUBSTITUI OS LS DA PALAVRA LITROS POR L
SELECT REPLACE(REPLACE(NOME_DO_PRODUTO,'Litro', 'L'), 'Ls', 'L') FROM TABELA_DE_PRODUTOS;







