-- PEGA A DATA DO SISTEMA
SELECT SYSDATE FROM DUAL;
-- CONVERTE A DATA DO SISTEMA PARA DIA MES ANO HORA MINUTO E SEGUNDO
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS') FROM DUAL;
-- CONVERTE A DATA DE NASCIMENTO DO CLIENTE PARA 10 MAIO 2002, SEXTA-FEIRA
SELECT NOME, TO_CHAR(DATA_DE_NASCIMENTO, 'DD MONTH YYYY, DAY') FROM TABELA_dE_CLIENTES;
-- VE A DATA DE HOJE + 127 DIAS 
SELECT SYSDATE + 127 FROM DUAL;
-- PEGA A IDADE DO CLIENTE FAZENDO O ANO ATUAL - ANO NASCIMENTO
SELECT NOME, IDADE, (SYSDATE - DATA_DE_NASCIMENTO)/365 AS IDADE_SISTEMA FROM TABELA_DE_CLIENTES;
-- PEGA A IDADE DO CLIENTE FAZENDO O ANO ATUAL - ANO NASCIMENTO UTILIZANDO FUNC MONTHS_BETWEEN
SELECT NOME, IDADE, MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO)/12 FROM TABELA_DE_CLIENTES;
-- ADICIONA MESES A DATA DO SISTEMA
SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL;
-- PEGA A PROXIMA DATA DO SISTEMA QUE TERA SEXTA-FEIRA
SELECT SYSDATE, NEXT_DAY(SYSDATE, 'SEXTA') FROM DUAL;
-- PEGA A ULTIMA DATA DO MES DO SISTEMA
SELECT SYSDATE, LAST_DAY(SYSDATE) FROM DUAL;
-- PEGA O PRIMEIRO DIA DO ANO (SE TROCAR O PARAMETRO YEAR E COLOCAR MONTH TAMBEM RETORNA O PRIMEIRO)
SELECT SYSDATE, TRUNC(SYSDATE, 'YEAR') FROM DUAL;
-- PEGA O PRIMEIRO DIA DO ANO SEGUINTE, POIS SYSDATE + 200 JA PASOSU DO MEIO DO ANO 
SELECT SYSDATE, ROUND(SYSDATE + 200, 'YEAR') FROM DUAL;

