SELECT 3.4 FROM DUAL;

SELECT ROUND(3.4) FROM DUAL;

SELECT ROUND(3.6) FROM DUAL;

SELECT ROUND(3.5) FROM DUAL;

SELECT TRUNC(3.4) FROM DUAL;

SELECT TRUNC(3.6) FROM DUAL;

SELECT TRUNC(3.5) FROM DUAL;

SELECT CEIL(3.4) FROM DUAL;

SELECT CEIL(3.6) FROM DUAL;

SELECT CEIL(3.5) FROM DUAL;

SELECT FLOOR(3.4) FROM DUAL;

SELECT FLOOR(3.6) FROM DUAL;

SELECT FLOOR(3.5) FROM DUAL;

SELECT POWER(10, 4) FROM DUAL;

SELECT EXP(4) FROM DUAL;

SELECT SQRT(81) FROM DUAL;

SELECT ABS(10) FROM DUAL;

SELECT ABS(-10) FROM DUAL;

SELECT MOD(10, 6) FROM DUAL;

