SELECT * FROM TABELA_DE_CLIENTES;

SELECT NF.CPF, 
TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') MES_ANO, 
SUM(INF.QUANTIDADE)QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY');

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA , TV.MES_ANO, TV.QUANTIDADE_TOTAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN (
SELECT NF.CPF, 
TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') MES_ANO, 
SUM(INF.QUANTIDADE)QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
)TV
ON TC.CPF = TV.CPF;

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA , TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= QUANTIDADE_TOTAL THEN 'VENDAS VALIDAS' 
ELSE 'VENDAS INVALIDAS' END) AS RESULTADO
FROM TABELA_DE_CLIENTES TC
INNER JOIN (
SELECT NF.CPF, 
TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') MES_ANO, 
SUM(INF.QUANTIDADE)QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
)TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015';

SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100,2)
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '02-2015'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0




