SELECT * FROM TB_PRODUTOS;

-- UM UPDATE
UPDATE TB_PRODUTOS SET EMBALAGEM = 'PET'
WHERE CODIGO_PRODUTO = '1037797';

-- UPDATE EM DIVERSAS COLUNAS
UPDATE TB_PRODUTOS SET 
NOME_PRODUTO = 'Videira do Campo - 1,5 Litros - Melância', 
TAMANHO = '1,5 Litros',
PRECO_LISTA = 19.51
WHERE CODIGO_PRODUTO = '1004327';

-- ALTERACAO DE COMISSAO DE VENDEDORES

SELECT * FROM TB_VENDEDORES
ORDER BY DATA_ADIMISSAO DESC;

UPDATE tb_VENDEDORES SET
PERCENTUAL_COMISSAO = 0.18
WHERE MATRICULA = '00810';

