INSERT INTO TB_PRODUTOS 
(CODIGO_PRODUTO,NOME_PRODUTO,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES 
('1004327', 'Videira do Campo - 1,5 Litros - Melância', 'PET', '1,5 Litros', 'Melância', 19.51);

INSERT INTO TB_PRODUTOS 
(CODIGO_PRODUTO,NOME_PRODUTO,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES 
('1088126', 'Linha Citros - 1 Litro - Limão', 'PET', '1 Litro', 'Limão', 7.00);

INSERT INTO TB_PRODUTOS 
(CODIGO_PRODUTO,NOME_PRODUTO,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES 
('544931', 'Frescor do Verão - 350 ml - Limão', 'Lata', '350 ml', 'Limão', 2.46);

SELECT * FROM TB_PRODUTOS;