INSERT INTO TB_VENDEDORES 
(MATRICULA, NOME_VENDEDOR, DATA_ADIMISSAO ,PERCENTUAL_COMISSAO)
VALUES ('00151', 'Gustavo Kehr', '10/05/2002' ,0.66);


SELECT * FROM TB_VENDEDORES;

INSERT INTO TB_VENDEDORES (MATRICULA, NOME_VENDEDOR, DATA_ADIMISSAO, 
PERCENTUAL_COMISSAO)
VALUES ('00265', 'John Wayne', TO_DATE('03/07/2019', 'MM/DD/YYYY'), 0.12);


UPDATE TB_VENDEDORES SET MATRICULA = '00233'
WHERE MATRICULA = '265';

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '265';


